-- DealFlow initial schema. Generated by hand to match lib/db/schema.ts.
-- Apply via `npm run db:migrate` (uses tsx + lib/db/migrate.ts).

CREATE TABLE IF NOT EXISTS "users" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text,
  "email" text NOT NULL,
  "emailVerified" timestamp,
  "image" text,
  "hashedPassword" text,
  "createdAt" timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "users_email_unique" ON "users" ("email");

CREATE TABLE IF NOT EXISTS "accounts" (
  "userId" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "type" text NOT NULL,
  "provider" text NOT NULL,
  "providerAccountId" text NOT NULL,
  "refresh_token" text,
  "access_token" text,
  "expires_at" integer,
  "token_type" text,
  "scope" text,
  "id_token" text,
  "session_state" text,
  PRIMARY KEY ("provider", "providerAccountId")
);

CREATE TABLE IF NOT EXISTS "sessions" (
  "sessionToken" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "expires" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "verificationTokens" (
  "identifier" text NOT NULL,
  "token" text NOT NULL,
  "expires" timestamp NOT NULL,
  PRIMARY KEY ("identifier", "token")
);

CREATE TABLE IF NOT EXISTS "workspaces" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "owner_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "created_at" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "workspace_members" (
  "workspace_id" text NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
  "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "role" text NOT NULL DEFAULT 'member',
  "created_at" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("workspace_id", "user_id")
);

CREATE INDEX IF NOT EXISTS "workspace_members_user_idx" ON "workspace_members" ("user_id");

CREATE TABLE IF NOT EXISTS "deals" (
  "id" text PRIMARY KEY NOT NULL,
  "workspace_id" text NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
  "created_by_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "business_type" text NOT NULL,
  "location" text NOT NULL DEFAULT '',
  "notes" text,
  "revenue" double precision NOT NULL DEFAULT 0,
  "rent" double precision NOT NULL DEFAULT 0,
  "labor_cost" double precision NOT NULL DEFAULT 0,
  "cogs" double precision NOT NULL DEFAULT 0,
  "utilities" double precision NOT NULL DEFAULT 0,
  "other_expenses" double precision NOT NULL DEFAULT 0,
  "owner_salary" double precision NOT NULL DEFAULT 0,
  "asking_price" double precision NOT NULL DEFAULT 0,
  "location_quality" integer,
  "growth_potential" integer,
  "owner_dependency" integer,
  "seasonality" integer,
  "status" text NOT NULL DEFAULT 'lead',
  "priority" text NOT NULL DEFAULT 'medium',
  "attachments" jsonb,
  "ai_narrative" jsonb,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "deals_workspace_idx" ON "deals" ("workspace_id", "created_at");
