"""Rome venues — clubs and dance floors (part 3 of 4)."""
from .generate_venues import club, lounge, rooftop
from .rome_data import _v


VENUES_PART3 = [
    _v(name="Shari Vari Playhouse", type="club", address="Via di Torre Argentina 78", lat=41.8956, lng=12.4778,
       neighborhood="Centro", opening_hours=club(("23:30", "04:30")), price_level=3, avg_price_eur=70,
       dress_code="elegant", music_types=["house", "hip_hop", "commercial"],
       vibe_tags=["trendy", "vip_friendly", "wild"], crowd_types=["international", "young", "vip"],
       guestlist_required=True, vip_available=True, capacity=400, quality_score=0.9, best_arrival_time="00:30"),
    _v(name="Spazio Novecento", type="club", address="Piazza Guglielmo Marconi 26", lat=41.8327, lng=12.4715,
       neighborhood="EUR", opening_hours=club(("23:30", "05:00")), price_level=3, avg_price_eur=60,
       dress_code="elegant", music_types=["house", "techno"], vibe_tags=["wild", "vip_friendly", "house_music"],
       crowd_types=["international", "young", "vip"], guestlist_required=True, vip_available=True, capacity=900,
       quality_score=0.88, best_arrival_time="01:00"),
    _v(name="Goa Club", type="club", address="Via Giuseppe Libetta 13", lat=41.8730, lng=12.5083,
       neighborhood="Ostiense", opening_hours=club(("23:30", "06:00")), price_level=3, avg_price_eur=45,
       music_types=["techno", "house"], vibe_tags=["wild", "techno", "underground"],
       crowd_types=["young", "locals", "international"], capacity=600, quality_score=0.92, best_arrival_time="01:00"),
    _v(name="Room 26", type="club", address="Piazza Guglielmo Marconi 31", lat=41.8327, lng=12.4710,
       neighborhood="EUR", opening_hours=club(("23:30", "05:00")), price_level=3, avg_price_eur=55,
       dress_code="elegant", music_types=["house", "hip_hop", "latin"],
       vibe_tags=["wild", "vip_friendly", "celebrity"], crowd_types=["young", "international", "vip"],
       guestlist_required=True, vip_available=True, capacity=800, quality_score=0.87, promoted=True,
       partner_status="pro", best_arrival_time="01:00"),
    _v(name="Coliseum Roma", type="club", address="Via Agide Pirazzini 5", lat=41.8826, lng=12.5125,
       neighborhood="Pigneto", opening_hours=club(("23:30", "05:00")), price_level=2, avg_price_eur=35,
       music_types=["latin", "reggaeton", "commercial"],
       vibe_tags=["latin", "lively", "wild"], crowd_types=["young", "international", "latin"],
       capacity=500, quality_score=0.83, best_arrival_time="00:30"),
    _v(name="Frida Music", type="club", address="Via dei Volsci 34", lat=41.8961, lng=12.5106,
       neighborhood="San Lorenzo", opening_hours=club(("23:00", "05:00")), price_level=2, avg_price_eur=30,
       music_types=["latin", "reggaeton", "kizomba"],
       vibe_tags=["latin", "wild", "social"], crowd_types=["young", "students", "international"],
       capacity=350, quality_score=0.82),
    _v(name="Lanificio 159", type="club", address="Via di Pietralata 159", lat=41.9118, lng=12.5510,
       neighborhood="Pigneto", opening_hours=club(("23:30", "05:00")), price_level=2, avg_price_eur=30,
       music_types=["techno", "electronic"], vibe_tags=["underground", "techno", "wild"],
       crowd_types=["locals", "young", "alternative"], capacity=600, quality_score=0.86, best_arrival_time="01:30"),
    _v(name="Akab Club", type="club", address="Via Monte Testaccio 69", lat=41.8767, lng=12.4757,
       neighborhood="Testaccio", opening_hours=club(("23:00", "05:00")), price_level=2, avg_price_eur=35,
       music_types=["hip_hop", "rnb", "house"], vibe_tags=["wild", "social", "lively"],
       crowd_types=["young", "international"], capacity=500, quality_score=0.84, best_arrival_time="00:30"),
    _v(name="Caruso Cafe de Oriente", type="club", address="Via di Monte Testaccio 36", lat=41.8767, lng=12.4757,
       neighborhood="Testaccio", opening_hours=club(("22:30", "04:30")), price_level=2, avg_price_eur=30,
       music_types=["latin", "salsa", "bachata"], vibe_tags=["latin", "lively", "social", "salsa"],
       crowd_types=["latin", "international", "young"], capacity=300, quality_score=0.85),
    _v(name="L'Alibi", type="club", address="Via di Monte Testaccio 39-44", lat=41.8767, lng=12.4757,
       neighborhood="Testaccio", opening_hours=club(("23:00", "05:00")), price_level=2, avg_price_eur=30,
       music_types=["house", "pop"], vibe_tags=["lgbtq_friendly", "wild", "social"],
       crowd_types=["young", "lgbtq", "international"], capacity=400, quality_score=0.83),
    _v(name="The Roof Hotel Hassler — Imàgo", type="rooftop", address="Piazza Trinità dei Monti 6", lat=41.9059, lng=12.4830,
       neighborhood="Centro", opening_hours=rooftop(("18:00", "01:00")), price_level=4, avg_price_eur=180,
       dress_code="elegant", music_types=["lounge"], vibe_tags=["luxury", "rooftop_view", "elegant", "michelin"],
       crowd_types=["date_friendly", "celebration", "couples"], reservation_required=True, vip_available=True,
       quality_score=0.97),
    _v(name="Settimo Roman Cuisine & Terrace", type="rooftop", address="Via Ludovisi 49", lat=41.9075, lng=12.4905,
       neighborhood="Centro", opening_hours=rooftop(("19:00", "01:00")), price_level=4, avg_price_eur=120,
       dress_code="elegant", music_types=["lounge"], vibe_tags=["luxury", "rooftop_view", "romantic"],
       crowd_types=["date_friendly", "international"], reservation_required=True, quality_score=0.93),
    _v(name="Divinity Lounge & Terrace", type="rooftop", address="Largo del Pallaro 8", lat=41.8961, lng=12.4738,
       neighborhood="Centro", opening_hours=rooftop(("18:00", "01:30")), price_level=3, avg_price_eur=70,
       music_types=["lounge", "house"], vibe_tags=["rooftop_view", "trendy", "romantic"],
       crowd_types=["date_friendly", "international"], reservation_required=True, quality_score=0.89),
    _v(name="Hotel Eitch Borromini Rooftop", type="rooftop", address="Via di Santa Maria dell'Anima 30", lat=41.8993, lng=12.4716,
       neighborhood="Centro", opening_hours=rooftop(("18:00", "00:30")), price_level=3, avg_price_eur=65,
       music_types=["lounge"], vibe_tags=["rooftop_view", "elegant", "romantic"],
       crowd_types=["date_friendly", "tourists", "international"], reservation_required=True, quality_score=0.91),
    _v(name="Terrazza Borromini", type="rooftop", address="Via di Santa Maria dell'Anima 31", lat=41.8995, lng=12.4716,
       neighborhood="Centro", opening_hours=rooftop(("18:00", "00:30")), price_level=4, avg_price_eur=90,
       dress_code="elegant", music_types=["lounge"], vibe_tags=["luxury", "rooftop_view", "romantic"],
       crowd_types=["date_friendly", "celebration"], reservation_required=True, vip_available=True,
       quality_score=0.94, promoted=True, partner_status="pro"),
]
