"""Rome venues — restaurants and aperitivo spots (part 1 of 4)."""
from .generate_venues import restaurant
from .rome_data import _v


VENUES_PART1 = [
    _v(name="Pierluigi", type="restaurant", address="Piazza de' Ricci 144", lat=41.8965, lng=12.4710,
       neighborhood="Centro", opening_hours=restaurant(("19:30", "23:30")), price_level=4, avg_price_eur=120,
       dress_code="elegant", cuisine_tags=["seafood", "italian"], vibe_tags=["elegant", "date_friendly", "romantic", "luxury"],
       crowd_types=["date_friendly", "international", "couples"], reservation_required=True, vip_available=True,
       quality_score=0.92, best_arrival_time="20:30"),
    _v(name="Roscioli", type="restaurant", address="Via dei Giubbonari 21", lat=41.8951, lng=12.4732,
       neighborhood="Centro", opening_hours=restaurant(("19:30", "00:00")), price_level=3, avg_price_eur=85,
       dress_code="casual", cuisine_tags=["italian", "wine_bar"], vibe_tags=["local_authentic", "trendy", "romantic"],
       crowd_types=["date_friendly", "international", "foodies"], reservation_required=True, quality_score=0.93),
    _v(name="Salumeria Roscioli", type="restaurant", address="Via dei Giubbonari 21/22", lat=41.8950, lng=12.4733,
       neighborhood="Centro", opening_hours=restaurant(("19:00", "23:30")), price_level=3, avg_price_eur=80,
       cuisine_tags=["italian", "salumi"], vibe_tags=["local", "authentic", "wine"], crowd_types=["foodies", "couples"],
       quality_score=0.9),
    _v(name="Pianostrada", type="restaurant", address="Via delle Zoccolette 22", lat=41.8929, lng=12.4730,
       neighborhood="Centro", opening_hours=restaurant(("19:30", "23:30")), price_level=3, avg_price_eur=70,
       cuisine_tags=["italian", "modern"], vibe_tags=["trendy", "romantic", "stylish"],
       crowd_types=["date_friendly", "international"], quality_score=0.89),
    _v(name="La Pergola", type="restaurant", address="Via Alberto Cadlolo 101", lat=41.9229, lng=12.4427,
       neighborhood="Centro", opening_hours=restaurant(("19:30", "23:00")), price_level=4, avg_price_eur=300,
       dress_code="luxury", cuisine_tags=["italian", "michelin"],
       vibe_tags=["luxury", "elegant", "romantic", "michelin"], crowd_types=["business", "celebration", "vip"],
       reservation_required=True, vip_available=True, quality_score=0.99, capacity=60),
    _v(name="Da Cesare al Casaletto", type="restaurant", address="Via del Casaletto 45", lat=41.8722, lng=12.4350,
       neighborhood="Trastevere", opening_hours=restaurant(("19:30", "23:30")), price_level=2, avg_price_eur=45,
       cuisine_tags=["roman", "trattoria"], vibe_tags=["local_authentic", "hidden_gem"],
       crowd_types=["locals", "foodies"], quality_score=0.91),
    _v(name="Da Enzo al 29", type="restaurant", address="Via dei Vascellari 29", lat=41.8881, lng=12.4769,
       neighborhood="Trastevere", opening_hours=restaurant(("19:30", "23:00")), price_level=2, avg_price_eur=40,
       cuisine_tags=["roman", "carbonara"], vibe_tags=["local_authentic", "tourist_friendly", "romantic"],
       crowd_types=["date_friendly", "international", "tourists"], quality_score=0.88),
    _v(name="Felice a Testaccio", type="restaurant", address="Via Mastro Giorgio 29", lat=41.8786, lng=12.4748,
       neighborhood="Testaccio", opening_hours=restaurant(("19:30", "23:30")), price_level=2, avg_price_eur=45,
       cuisine_tags=["roman", "cacio_e_pepe"], vibe_tags=["local_authentic", "lively"],
       crowd_types=["foodies", "groups"], quality_score=0.9),
    _v(name="Tonnarello", type="restaurant", address="Via della Paglia 1/2/3", lat=41.8896, lng=12.4685,
       neighborhood="Trastevere", opening_hours=restaurant(("12:00", "00:00")), price_level=2, avg_price_eur=35,
       cuisine_tags=["roman"], vibe_tags=["lively", "tourist_friendly"], crowd_types=["groups", "tourists"],
       quality_score=0.82),
    _v(name="Hostaria Romana", type="restaurant", address="Via del Boccaccio 1", lat=41.9024, lng=12.4884,
       neighborhood="Centro", opening_hours=restaurant(("19:00", "23:30")), price_level=2, avg_price_eur=50,
       cuisine_tags=["roman"], vibe_tags=["local", "romantic"], crowd_types=["date_friendly", "tourists"],
       quality_score=0.85),
    _v(name="Il Pagliaccio", type="restaurant", address="Via dei Banchi Vecchi 129", lat=41.8983, lng=12.4685,
       neighborhood="Centro", opening_hours=restaurant(("19:30", "22:30")), price_level=4, avg_price_eur=200,
       dress_code="elegant", cuisine_tags=["italian", "michelin"], vibe_tags=["luxury", "michelin", "elegant"],
       crowd_types=["business", "celebration"], reservation_required=True, vip_available=True, quality_score=0.96),
    _v(name="Glass Hostaria", type="restaurant", address="Vicolo del Cinque 58", lat=41.8893, lng=12.4691,
       neighborhood="Trastevere", opening_hours=restaurant(("20:00", "23:00")), price_level=4, avg_price_eur=130,
       dress_code="elegant", cuisine_tags=["italian", "michelin"], vibe_tags=["luxury", "romantic", "michelin"],
       crowd_types=["date_friendly", "couples"], reservation_required=True, quality_score=0.94),
    _v(name="Marco Martini Restaurant", type="restaurant", address="Viale Aventino 121", lat=41.8829, lng=12.4848,
       neighborhood="Aventino", opening_hours=restaurant(("19:30", "22:30")), price_level=4, avg_price_eur=140,
       dress_code="elegant", cuisine_tags=["italian", "modern"], vibe_tags=["luxury", "romantic", "trendy"],
       crowd_types=["date_friendly"], reservation_required=True, quality_score=0.92),
    _v(name="Mercato Centrale Roma", type="restaurant", address="Via Giovanni Giolitti 36", lat=41.9008, lng=12.5026,
       neighborhood="Centro", opening_hours=restaurant(("12:00", "00:00")), price_level=2, avg_price_eur=30,
       cuisine_tags=["food_hall", "italian"], vibe_tags=["lively", "social"], crowd_types=["groups", "international"],
       quality_score=0.8),
    _v(name="Trattoria Da Teo", type="restaurant", address="Piazza dei Ponziani 7", lat=41.8884, lng=12.4760,
       neighborhood="Trastevere", opening_hours=restaurant(("19:30", "23:30")), price_level=2, avg_price_eur=45,
       cuisine_tags=["roman"], vibe_tags=["local_authentic", "romantic"], crowd_types=["date_friendly", "tourists"],
       quality_score=0.86),
]
