"""Rome venues — bars, lounges, speakeasies, rooftops (part 2 of 4)."""
from .generate_venues import bar, lounge, rooftop, speakeasy
from .rome_data import _v


VENUES_PART2 = [
    _v(name="Jerry Thomas Speakeasy", type="speakeasy", address="Vicolo Cellini 30", lat=41.8980, lng=12.4694,
       neighborhood="Centro", opening_hours=speakeasy(("19:30", "02:30")), price_level=3, avg_price_eur=60,
       dress_code="elegant", music_types=["jazz", "swing"], vibe_tags=["hidden_gem", "speakeasy", "romantic", "trendy"],
       crowd_types=["date_friendly", "international"], reservation_required=True, quality_score=0.94,
       best_arrival_time="22:00"),
    _v(name="The Court at Palazzo Manfredi", type="lounge", address="Via Labicana 125", lat=41.8893, lng=12.4944,
       neighborhood="Centro", opening_hours=lounge(("18:00", "01:00")), price_level=4, avg_price_eur=90,
       dress_code="elegant", music_types=["lounge", "deep_house"], vibe_tags=["luxury", "romantic", "rooftop_view"],
       crowd_types=["date_friendly", "international"], vip_available=True, reservation_required=True,
       quality_score=0.95, best_arrival_time="20:00"),
    _v(name="Stravinskij Bar — Hotel de Russie", type="lounge", address="Via del Babuino 9", lat=41.9080, lng=12.4768,
       neighborhood="Centro", opening_hours=lounge(("11:00", "01:00")), price_level=4, avg_price_eur=80,
       dress_code="elegant", music_types=["lounge", "jazz"], vibe_tags=["luxury", "romantic", "elegant"],
       crowd_types=["business", "international", "couples"], reservation_required=True, vip_available=True,
       quality_score=0.97),
    _v(name="The Race Club Speakeasy", type="speakeasy", address="Via Labicana 52", lat=41.8896, lng=12.4960,
       neighborhood="Centro", opening_hours=speakeasy(("20:00", "02:30")), price_level=3, avg_price_eur=55,
       music_types=["jazz", "soul"], vibe_tags=["speakeasy", "hidden_gem", "trendy"],
       crowd_types=["date_friendly", "locals"], reservation_required=True, quality_score=0.9),
    _v(name="Argot", type="speakeasy", address="Via dei Cappellari 93", lat=41.8957, lng=12.4691,
       neighborhood="Centro", opening_hours=speakeasy(("19:00", "02:00")), price_level=3, avg_price_eur=50,
       music_types=["jazz"], vibe_tags=["hidden_gem", "romantic", "speakeasy"],
       crowd_types=["date_friendly", "locals"], reservation_required=True, quality_score=0.92),
    _v(name="Salotto 42", type="bar", address="Piazza di Pietra 42", lat=41.9000, lng=12.4811,
       neighborhood="Centro", opening_hours=bar(("18:00", "02:00")), price_level=3, avg_price_eur=45,
       music_types=["lounge"], vibe_tags=["trendy", "elegant", "after_work"],
       crowd_types=["international", "date_friendly"], quality_score=0.88),
    _v(name="Freni e Frizioni", type="bar", address="Via del Politeama 4-6", lat=41.8888, lng=12.4683,
       neighborhood="Trastevere", opening_hours=bar(("18:30", "02:00")), price_level=2, avg_price_eur=25,
       music_types=["indie", "electronic"], vibe_tags=["aperitivo", "lively", "local_authentic"],
       crowd_types=["locals", "students", "international"], quality_score=0.85),
    _v(name="Ma Che Siete Venuti A Fa", type="bar", address="Via di Benedetta 25", lat=41.8895, lng=12.4691,
       neighborhood="Trastevere", opening_hours=bar(("17:00", "02:00")), price_level=2, avg_price_eur=20,
       music_types=["rock"], vibe_tags=["pub", "local", "lively"], crowd_types=["locals", "international"],
       quality_score=0.86),
    _v(name="Co.So Cocktails & Social", type="bar", address="Via Braccio da Montone 80", lat=41.8907, lng=12.5154,
       neighborhood="Pigneto", opening_hours=bar(("18:00", "02:00")), price_level=2, avg_price_eur=35,
       music_types=["electronic", "house"], vibe_tags=["trendy", "local", "hipster"],
       crowd_types=["locals", "young"], quality_score=0.89),
    _v(name="Bar San Calisto", type="bar", address="Piazza di San Calisto 4", lat=41.8881, lng=12.4707,
       neighborhood="Trastevere", opening_hours=bar(("06:00", "02:00")), price_level=1, avg_price_eur=10,
       music_types=["none"], vibe_tags=["local_authentic", "hidden_gem", "budget"],
       crowd_types=["locals"], quality_score=0.83),
    _v(name="Drink Kong", type="bar", address="Piazza di San Martino ai Monti 8", lat=41.8965, lng=12.4990,
       neighborhood="Monti", opening_hours=bar(("19:00", "02:00")), price_level=3, avg_price_eur=50,
       music_types=["electronic", "synthwave"], vibe_tags=["trendy", "stylish", "international"],
       crowd_types=["international", "young"], reservation_required=True, quality_score=0.93),
    _v(name="Hotel Locarno Bar", type="lounge", address="Via della Penna 22", lat=41.9100, lng=12.4760,
       neighborhood="Centro", opening_hours=lounge(("17:00", "01:00")), price_level=3, avg_price_eur=45,
       music_types=["jazz", "lounge"], vibe_tags=["elegant", "romantic", "art_deco"],
       crowd_types=["date_friendly", "international"], quality_score=0.9),
    _v(name="Spirito", type="speakeasy", address="Via Fanfulla da Lodi 53", lat=41.8893, lng=12.5128,
       neighborhood="Pigneto", opening_hours=speakeasy(("19:00", "02:00")), price_level=3, avg_price_eur=50,
       music_types=["funk", "soul"], vibe_tags=["hidden_gem", "speakeasy", "trendy"],
       crowd_types=["locals", "date_friendly"], reservation_required=True, quality_score=0.91),
    _v(name="Hotel Cavalieri Roma — La Pergola Bar", type="lounge", address="Via Alberto Cadlolo 101", lat=41.9229, lng=12.4427,
       neighborhood="Centro", opening_hours=lounge(("18:00", "00:30")), price_level=4, avg_price_eur=80,
       dress_code="elegant", music_types=["lounge"], vibe_tags=["luxury", "elegant", "rooftop_view"],
       crowd_types=["business", "international"], vip_available=True, reservation_required=True, quality_score=0.95),
    _v(name="Aroma Restaurant — Palazzo Manfredi Rooftop", type="rooftop", address="Via Labicana 125", lat=41.8893, lng=12.4944,
       neighborhood="Centro", opening_hours=rooftop(("18:00", "00:00")), price_level=4, avg_price_eur=180,
       dress_code="elegant", music_types=["lounge"], vibe_tags=["luxury", "romantic", "rooftop_view", "michelin"],
       crowd_types=["date_friendly", "celebration", "couples"], reservation_required=True, vip_available=True,
       quality_score=0.97, promoted=True, partner_status="premium"),
]
