"""Rome venues — live music + late-night food + extras (part 4 of 4)."""
from .generate_venues import bar, late_food, live_music, restaurant
from .rome_data import _v


VENUES_PART4 = [
    _v(name="Big Mama Trastevere", type="live_music", address="Vicolo di San Francesco a Ripa 18", lat=41.8859, lng=12.4716,
       neighborhood="Trastevere", opening_hours=live_music(("21:00", "02:00")), price_level=2, avg_price_eur=30,
       music_types=["blues", "jazz", "rock"], vibe_tags=["live_music", "local", "intimate"],
       crowd_types=["locals", "international"], capacity=200, quality_score=0.88),
    _v(name="Cotton Club", type="live_music", address="Via Bellinzona 2", lat=41.9210, lng=12.4925,
       neighborhood="Centro", opening_hours=live_music(("21:00", "02:00")), price_level=2, avg_price_eur=30,
       music_types=["jazz", "swing"], vibe_tags=["live_music", "jazz", "intimate"],
       crowd_types=["locals", "international"], capacity=180, quality_score=0.87),
    _v(name="Alexanderplatz Jazz Club", type="live_music", address="Via Ostia 9", lat=41.9072, lng=12.4509,
       neighborhood="Prati", opening_hours=live_music(("21:00", "02:00")), price_level=3, avg_price_eur=40,
       music_types=["jazz"], vibe_tags=["jazz", "live_music", "elegant"],
       crowd_types=["date_friendly", "international"], reservation_required=True, capacity=150, quality_score=0.92),
    _v(name="Fonclea", type="live_music", address="Via Crescenzio 82A", lat=41.9061, lng=12.4623,
       neighborhood="Prati", opening_hours=live_music(("20:30", "02:00")), price_level=2, avg_price_eur=30,
       music_types=["rock", "blues", "soul"], vibe_tags=["live_music", "local"],
       crowd_types=["locals", "international"], capacity=200, quality_score=0.85),
    _v(name="Pinsere", type="late_food", address="Via Flavia 98", lat=41.9075, lng=12.4985,
       neighborhood="Centro", opening_hours=late_food(("12:00", "23:00")), price_level=1, avg_price_eur=12,
       cuisine_tags=["pinsa", "pizza"], vibe_tags=["budget", "quick_bite"], crowd_types=["locals", "tourists"],
       quality_score=0.85),
    _v(name="Trapizzino — Trastevere", type="late_food", address="Piazza Trilussa 46", lat=41.8898, lng=12.4685,
       neighborhood="Trastevere", opening_hours=late_food(("12:00", "01:00")), price_level=1, avg_price_eur=12,
       cuisine_tags=["roman", "street_food"], vibe_tags=["budget", "late_night", "local"],
       crowd_types=["locals", "international"], quality_score=0.88),
    _v(name="Supplì Roma", type="late_food", address="Via di San Francesco a Ripa 137", lat=41.8868, lng=12.4724,
       neighborhood="Trastevere", opening_hours=late_food(("11:00", "23:00")), price_level=1, avg_price_eur=10,
       cuisine_tags=["roman", "street_food"], vibe_tags=["budget", "quick_bite"], crowd_types=["locals", "tourists"],
       quality_score=0.86),
    _v(name="Bonci Pizzarium", type="late_food", address="Via della Meloria 43", lat=41.9070, lng=12.4396,
       neighborhood="Prati", opening_hours=late_food(("11:00", "22:00")), price_level=2, avg_price_eur=18,
       cuisine_tags=["pizza"], vibe_tags=["foodies", "trendy"], crowd_types=["foodies", "tourists"],
       quality_score=0.93),
    _v(name="Pizzeria Ai Marmi", type="late_food", address="Viale di Trastevere 53", lat=41.8851, lng=12.4715,
       neighborhood="Trastevere", opening_hours=late_food(("19:00", "01:30")), price_level=1, avg_price_eur=18,
       cuisine_tags=["pizza", "roman"], vibe_tags=["lively", "local", "late_night"],
       crowd_types=["locals", "groups"], quality_score=0.84),
    _v(name="Forno Roscioli", type="late_food", address="Via dei Chiavari 34", lat=41.8949, lng=12.4732,
       neighborhood="Centro", opening_hours=late_food(("07:00", "20:00")), price_level=1, avg_price_eur=10,
       cuisine_tags=["pizza_al_taglio", "bakery"], vibe_tags=["local", "budget"],
       crowd_types=["locals", "tourists"], quality_score=0.91),
    _v(name="Grezzo Raw Chocolate", type="late_food", address="Via Urbana 130", lat=41.8961, lng=12.4955,
       neighborhood="Monti", opening_hours=late_food(("11:00", "23:00")), price_level=2, avg_price_eur=14,
       cuisine_tags=["dessert", "vegan"], vibe_tags=["trendy", "vegan", "date_friendly"],
       crowd_types=["date_friendly", "foodies"], quality_score=0.87),
    _v(name="Chorus Cafe", type="lounge", address="Via della Conciliazione 4/A", lat=41.9011, lng=12.4595,
       neighborhood="Prati", opening_hours=bar(("18:00", "01:30")), price_level=3, avg_price_eur=55,
       music_types=["lounge", "jazz"], vibe_tags=["elegant", "rooftop_view", "romantic"],
       crowd_types=["date_friendly", "international"], reservation_required=True, quality_score=0.9),
    _v(name="The Garden Bar — Hotel de la Ville", type="lounge", address="Via Sistina 69", lat=41.9067, lng=12.4858,
       neighborhood="Centro", opening_hours=bar(("17:00", "01:00")), price_level=4, avg_price_eur=70,
       dress_code="elegant", music_types=["lounge"], vibe_tags=["luxury", "elegant", "rooftop_view"],
       crowd_types=["business", "international"], vip_available=True, quality_score=0.95),
    _v(name="Zuma Roma", type="restaurant", address="Via della Fontanella di Borghese 48", lat=41.9039, lng=12.4790,
       neighborhood="Centro", opening_hours=restaurant(("19:00", "00:00")), price_level=4, avg_price_eur=150,
       dress_code="elegant", cuisine_tags=["japanese", "robata"],
       vibe_tags=["luxury", "trendy", "international"], crowd_types=["business", "international", "celebrities"],
       reservation_required=True, vip_available=True, quality_score=0.96, promoted=True, partner_status="premium"),
    _v(name="Hostaria dell'Orso", type="restaurant", address="Via dei Soldati 25", lat=41.9018, lng=12.4730,
       neighborhood="Centro", opening_hours=restaurant(("20:00", "01:00")), price_level=4, avg_price_eur=140,
       dress_code="elegant", cuisine_tags=["italian"], vibe_tags=["luxury", "elegant", "romantic", "historic"],
       crowd_types=["date_friendly", "celebration"], reservation_required=True, vip_available=True, quality_score=0.91),
]
