"""baseline

Revision ID: a77e6122ea48
Revises: 
Create Date: 2026-04-28 21:35:21.300461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77e6122ea48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('clock_in', sa.String(length=10), nullable=False),
    sa.Column('clock_out', sa.String(length=10), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_time_logs_id'), 'staff_time_logs', ['id'], unique=False)
    op.create_index(op.f('ix_staff_time_logs_user_id'), 'staff_time_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('social_provider', sa.String(length=50), nullable=True),
    sa.Column('social_id', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('music_genres', sa.Text(), nullable=True),
    sa.Column('cuisine_preferences', sa.Text(), nullable=True),
    sa.Column('dietary_preferences', sa.Text(), nullable=True),
    sa.Column('drinking_habits', sa.Text(), nullable=True),
    sa.Column('recipe_interests', sa.Text(), nullable=True),
    sa.Column('kitchen_style', sa.String(length=100), nullable=True),
    sa.Column('skill_level', sa.String(length=50), nullable=True),
    sa.Column('cooking_frequency', sa.String(length=50), nullable=True),
    sa.Column('cooking_time_pref', sa.String(length=50), nullable=True),
    sa.Column('flavor_profile', sa.Text(), nullable=True),
    sa.Column('cooking_goals', sa.Text(), nullable=True),
    sa.Column('meal_types', sa.Text(), nullable=True),
    sa.Column('kitchen_tools', sa.Text(), nullable=True),
    sa.Column('ingredient_budget', sa.String(length=50), nullable=True),
    sa.Column('music_moods', sa.Text(), nullable=True),
    sa.Column('non_alcoholic_ok', sa.Boolean(), nullable=True),
    sa.Column('cuisine_dislikes', sa.Text(), nullable=True),
    sa.Column('dining_occasions', sa.Text(), nullable=True),
    sa.Column('atmosphere_prefs', sa.Text(), nullable=True),
    sa.Column('dining_budget', sa.String(length=50), nullable=True),
    sa.Column('dining_frequency', sa.String(length=50), nullable=True),
    sa.Column('dining_group', sa.Text(), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('restaurant_cuisine', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Text(), nullable=True),
    sa.Column('dining_style', sa.String(length=50), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('peak_hours', sa.Text(), nullable=True),
    sa.Column('restaurant_goals', sa.Text(), nullable=True),
    sa.Column('wine_program', sa.Text(), nullable=True),
    sa.Column('seating_capacity', sa.Integer(), nullable=True),
    sa.Column('serves_wine', sa.Boolean(), nullable=True),
    sa.Column('serves_cocktails', sa.Boolean(), nullable=True),
    sa.Column('serves_beer', sa.Boolean(), nullable=True),
    sa.Column('available_time_slots', sa.Text(), nullable=True),
    sa.Column('booking_window_days', sa.Integer(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_logs_id'), 'behavior_logs', ['id'], unique=False)
    op.create_index(op.f('ix_behavior_logs_user_id'), 'behavior_logs', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('diner_user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['diner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('crm_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('total_spend', sa.Float(), nullable=True),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('favorite_items', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_customers_id'), 'crm_customers', ['id'], unique=False)
    op.create_index(op.f('ix_crm_customers_user_id'), 'crm_customers', ['user_id'], unique=False)
    op.create_table('diner_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=150), nullable=False),
    sa.Column('booking_date', sa.String(length=20), nullable=False),
    sa.Column('booking_time', sa.String(length=10), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('restaurant_user_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diner_bookings_id'), 'diner_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_diner_bookings_user_id'), 'diner_bookings', ['user_id'], unique=False)
    op.create_table('diner_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diner_user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['diner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diner_reviews_diner_user_id'), 'diner_reviews', ['diner_user_id'], unique=False)
    op.create_index(op.f('ix_diner_reviews_id'), 'diner_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_diner_reviews_restaurant_user_id'), 'diner_reviews', ['restaurant_user_id'], unique=False)
    op.create_table('diner_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=150), nullable=False),
    sa.Column('visit_date', sa.String(length=20), nullable=False),
    sa.Column('items_ordered', sa.Text(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('food_rating', sa.Float(), nullable=True),
    sa.Column('staff_rating', sa.Float(), nullable=True),
    sa.Column('would_return', sa.Boolean(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('lowlights', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diner_visits_id'), 'diner_visits', ['id'], unique=False)
    op.create_index(op.f('ix_diner_visits_user_id'), 'diner_visits', ['user_id'], unique=False)
    op.create_table('dish_time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('prep_minutes', sa.Float(), nullable=False),
    sa.Column('cook_minutes', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_time_logs_id'), 'dish_time_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dish_time_logs_user_id'), 'dish_time_logs', ['user_id'], unique=False)
    op.create_table('food_waste_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_waste_logs_id'), 'food_waste_logs', ['id'], unique=False)
    op.create_index(op.f('ix_food_waste_logs_user_id'), 'food_waste_logs', ['user_id'], unique=False)
    op.create_table('meal_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=150), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('what_id_change', sa.Text(), nullable=True),
    sa.Column('cuisine', sa.String(length=100), nullable=True),
    sa.Column('cooked_at', sa.DateTime(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_memories_id'), 'meal_memories', ['id'], unique=False)
    op.create_index(op.f('ix_meal_memories_user_id'), 'meal_memories', ['user_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('orders_last_30_days', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_items_user_id'), 'menu_items', ['user_id'], unique=False)
    op.create_table('music_moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('food_type', sa.String(), nullable=True),
    sa.Column('occasion', sa.String(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_moods_id'), 'music_moods', ['id'], unique=False)
    op.create_index(op.f('ix_music_moods_user_id'), 'music_moods', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('pantry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_items_id'), 'pantry_items', ['id'], unique=False)
    op.create_index(op.f('ix_pantry_items_user_id'), 'pantry_items', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('menu_item', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('sales_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_logs_id'), 'sales_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sales_logs_user_id'), 'sales_logs', ['user_id'], unique=False)
    op.create_table('social_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_connections_id'), 'social_connections', ['id'], unique=False)
    op.create_index(op.f('ix_social_connections_user_id'), 'social_connections', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('orders_handled', sa.Integer(), nullable=True),
    sa.Column('avg_order_value', sa.Float(), nullable=True),
    sa.Column('punctuality_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=False)
    op.create_table('wine_pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(), nullable=False),
    sa.Column('dish_description', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wine_pairings_id'), 'wine_pairings', ['id'], unique=False)
    op.create_index(op.f('ix_wine_pairings_user_id'), 'wine_pairings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wine_pairings_user_id'), table_name='wine_pairings')
    op.drop_index(op.f('ix_wine_pairings_id'), table_name='wine_pairings')
    op.drop_table('wine_pairings')
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_social_connections_user_id'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_id'), table_name='social_connections')
    op.drop_table('social_connections')
    op.drop_index(op.f('ix_sales_logs_user_id'), table_name='sales_logs')
    op.drop_index(op.f('ix_sales_logs_id'), table_name='sales_logs')
    op.drop_table('sales_logs')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_pantry_items_user_id'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_id'), table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_music_moods_user_id'), table_name='music_moods')
    op.drop_index(op.f('ix_music_moods_id'), table_name='music_moods')
    op.drop_table('music_moods')
    op.drop_index(op.f('ix_menu_items_user_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_meal_memories_user_id'), table_name='meal_memories')
    op.drop_index(op.f('ix_meal_memories_id'), table_name='meal_memories')
    op.drop_table('meal_memories')
    op.drop_index(op.f('ix_food_waste_logs_user_id'), table_name='food_waste_logs')
    op.drop_index(op.f('ix_food_waste_logs_id'), table_name='food_waste_logs')
    op.drop_table('food_waste_logs')
    op.drop_index(op.f('ix_dish_time_logs_user_id'), table_name='dish_time_logs')
    op.drop_index(op.f('ix_dish_time_logs_id'), table_name='dish_time_logs')
    op.drop_table('dish_time_logs')
    op.drop_index(op.f('ix_diner_visits_user_id'), table_name='diner_visits')
    op.drop_index(op.f('ix_diner_visits_id'), table_name='diner_visits')
    op.drop_table('diner_visits')
    op.drop_index(op.f('ix_diner_reviews_restaurant_user_id'), table_name='diner_reviews')
    op.drop_index(op.f('ix_diner_reviews_id'), table_name='diner_reviews')
    op.drop_index(op.f('ix_diner_reviews_diner_user_id'), table_name='diner_reviews')
    op.drop_table('diner_reviews')
    op.drop_index(op.f('ix_diner_bookings_user_id'), table_name='diner_bookings')
    op.drop_index(op.f('ix_diner_bookings_id'), table_name='diner_bookings')
    op.drop_table('diner_bookings')
    op.drop_index(op.f('ix_crm_customers_user_id'), table_name='crm_customers')
    op.drop_index(op.f('ix_crm_customers_id'), table_name='crm_customers')
    op.drop_table('crm_customers')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_behavior_logs_user_id'), table_name='behavior_logs')
    op.drop_index(op.f('ix_behavior_logs_id'), table_name='behavior_logs')
    op.drop_table('behavior_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staff_time_logs_user_id'), table_name='staff_time_logs')
    op.drop_index(op.f('ix_staff_time_logs_id'), table_name='staff_time_logs')
    op.drop_table('staff_time_logs')
    # ### end Alembic commands ###
