"""home services vertical

Revision ID: b0facfa05ea0
Revises: a77e6122ea48
Create Date: 2026-04-29 13:31:34.024810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0facfa05ea0'
down_revision: Union[str, None] = 'a77e6122ea48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('provider_type', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('service_radius_km', sa.Float(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('minimum_fee', sa.Float(), nullable=True),
    sa.Column('travel_fee', sa.Float(), nullable=True),
    sa.Column('emergency_fee', sa.Float(), nullable=True),
    sa.Column('accepts_emergency', sa.Boolean(), nullable=True),
    sa.Column('verified_status', sa.String(length=20), nullable=True),
    sa.Column('insurance_status', sa.String(length=20), nullable=True),
    sa.Column('license_status', sa.String(length=20), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('completed_jobs', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('cancellation_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_providers_id'), 'home_providers', ['id'], unique=False)
    op.create_index(op.f('ix_home_providers_user_id'), 'home_providers', ['user_id'], unique=True)
    op.create_table('home_job_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('booking_type', sa.String(length=20), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('preferred_start', sa.DateTime(), nullable=True),
    sa.Column('preferred_end', sa.DateTime(), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('target_provider_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_provider_id'], ['home_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_job_requests_category'), 'home_job_requests', ['category'], unique=False)
    op.create_index(op.f('ix_home_job_requests_customer_user_id'), 'home_job_requests', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_home_job_requests_id'), 'home_job_requests', ['id'], unique=False)
    op.create_table('home_provider_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pricing_type', sa.String(length=20), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('minimum_fee', sa.Float(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('materials_included', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['home_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_provider_services_category'), 'home_provider_services', ['category'], unique=False)
    op.create_index(op.f('ix_home_provider_services_id'), 'home_provider_services', ['id'], unique=False)
    op.create_index(op.f('ix_home_provider_services_provider_id'), 'home_provider_services', ['provider_id'], unique=False)
    op.create_table('home_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('materials_cost', sa.Float(), nullable=True),
    sa.Column('travel_fee', sa.Float(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('earliest_start', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['home_job_requests.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['home_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_quotes_id'), 'home_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_home_quotes_job_id'), 'home_quotes', ['job_id'], unique=False)
    op.create_index(op.f('ix_home_quotes_provider_id'), 'home_quotes', ['provider_id'], unique=False)
    op.create_table('home_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('provider_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['home_job_requests.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['home_providers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['home_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_bookings_customer_user_id'), 'home_bookings', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_home_bookings_id'), 'home_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_home_bookings_job_id'), 'home_bookings', ['job_id'], unique=False)
    op.create_index(op.f('ix_home_bookings_provider_id'), 'home_bookings', ['provider_id'], unique=False)
    op.create_table('home_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('quality_rating', sa.Float(), nullable=True),
    sa.Column('punctuality_rating', sa.Float(), nullable=True),
    sa.Column('communication_rating', sa.Float(), nullable=True),
    sa.Column('price_accuracy_rating', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['home_bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['home_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_reviews_booking_id'), 'home_reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_home_reviews_customer_user_id'), 'home_reviews', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_home_reviews_id'), 'home_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_home_reviews_provider_id'), 'home_reviews', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_reviews_provider_id'), table_name='home_reviews')
    op.drop_index(op.f('ix_home_reviews_id'), table_name='home_reviews')
    op.drop_index(op.f('ix_home_reviews_customer_user_id'), table_name='home_reviews')
    op.drop_index(op.f('ix_home_reviews_booking_id'), table_name='home_reviews')
    op.drop_table('home_reviews')
    op.drop_index(op.f('ix_home_bookings_provider_id'), table_name='home_bookings')
    op.drop_index(op.f('ix_home_bookings_job_id'), table_name='home_bookings')
    op.drop_index(op.f('ix_home_bookings_id'), table_name='home_bookings')
    op.drop_index(op.f('ix_home_bookings_customer_user_id'), table_name='home_bookings')
    op.drop_table('home_bookings')
    op.drop_index(op.f('ix_home_quotes_provider_id'), table_name='home_quotes')
    op.drop_index(op.f('ix_home_quotes_job_id'), table_name='home_quotes')
    op.drop_index(op.f('ix_home_quotes_id'), table_name='home_quotes')
    op.drop_table('home_quotes')
    op.drop_index(op.f('ix_home_provider_services_provider_id'), table_name='home_provider_services')
    op.drop_index(op.f('ix_home_provider_services_id'), table_name='home_provider_services')
    op.drop_index(op.f('ix_home_provider_services_category'), table_name='home_provider_services')
    op.drop_table('home_provider_services')
    op.drop_index(op.f('ix_home_job_requests_id'), table_name='home_job_requests')
    op.drop_index(op.f('ix_home_job_requests_customer_user_id'), table_name='home_job_requests')
    op.drop_index(op.f('ix_home_job_requests_category'), table_name='home_job_requests')
    op.drop_table('home_job_requests')
    op.drop_index(op.f('ix_home_providers_user_id'), table_name='home_providers')
    op.drop_index(op.f('ix_home_providers_id'), table_name='home_providers')
    op.drop_table('home_providers')
    # ### end Alembic commands ###
